In [10]:
import numpy as np


nama_array = np.array([1, 2, 3])
np.zeros(6)
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [12]:
print(np.arange(4))
print(np.arange(0,10,2)) # (start, stop, step)

[0 1 2 3]
[0 2 4 6 8]


In [13]:
np.arange(2,29,5) #range data 2 - 29, dengan n1+5

array([ 2,  7, 12, 17, 22, 27])

In [39]:
#Add, Remove, and Sort
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr = np.append(arr, [10,12])


In [40]:
arr=np.delete(arr, 0) #menghapus data ke-0
arr=np.delete(arr, 0)
arr

array([ 3,  4,  5,  6,  7,  8, 10, 12])

In [42]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [43]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [44]:
array_example.ndim #dimensi

3

In [45]:
array_example.size

24

In [46]:
array_example.shape

(3, 2, 4)

In [47]:
arr_one = np.array([[1, 2, 3, 4, 5]])

In [48]:
arr_one.ndim

2

In [49]:
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


In [50]:
b = a.reshape(3,2)

print(b)

[[0 1]
 [2 3]
 [4 5]]


In [51]:
a.reshape(6,1) #inverse matrik --> 6 x 1

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [52]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [53]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [55]:
row_vector = a[np.newaxis, :]
print(row_vector)
print(row_vector.shape)
print(row_vector)

[[1 2 3 4 5 6]]
(1, 6)
[[1 2 3 4 5 6]]


In [56]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)


(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [57]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [62]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [63]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [65]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[0:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[1 2 3]
[2 3]


In [66]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [67]:
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [77]:
five_up = (a >= 5)

print(a[five_up])
print(a[(a>=5)&(a<10)])

[ 5  6  7  8  9 10 11 12]
[5 6 7 8 9]


In [78]:
arr = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [83]:
a_1 = np.array([[1, 1],
                [2, 2]])
a_2 = np.array([[3, 3],
                [4, 4]])
aa= np.vstack((a_1, a_2)) #vertical

In [84]:
aa

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [85]:
np.hstack((a_1, a_2)) #horizontal

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [87]:
arrsplit = np.array([[1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
                     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [90]:
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [91]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [92]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [94]:
c = a.copy()
d = c
c,d

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]))

In [95]:
a = np.array([1, 2, 3, 4])

# Add all of the elements in the array
a.sum()

10

In [96]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [97]:
b.sum(axis=0) #perhitungan kebawah

array([3, 3])

In [98]:
b.sum(axis=1) #perhitungan kesamping

array([2, 4])

In [99]:
data = np.array([1, 2])
data

array([1, 2])

In [100]:
ones = np.ones(2)
ones

array([1., 1.])

In [102]:
data + ones

array([2., 3.])

In [103]:
data * data

array([1, 4])

In [104]:
data / data

array([1., 1.])

In [105]:
data*100

array([100, 200])

In [106]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [109]:
round(A.sum(),2)

4.86

In [110]:
round(A.min(),2)

0.05

In [111]:
A.min(axis=0) #nilai minimum di masing-masing axis

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [112]:
round(A.max(),2)

0.82

In [113]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [114]:
A.max(axis=0)

array([0.54627315, 0.82485143, 0.40067661, 0.56917101])

In [115]:
A.std()

0.21392120766089617

In [116]:
A.mean()

0.4049648666666667

In [120]:
np.ones((3,2)) #matrik 3x2 berisi nilai 1
np.zeros((3,2)) #matrik 3x2 berisi nilai 0
np.random.random((3,2))#matrik 3x2 berisi nilai random
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.53383083 0.56439247]
 [0.40809947 0.74332877]
 [0.56886032 0.06891886]]


In [121]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [122]:
np.dot(a_1, a_2)


array([[ 58,  64],
       [139, 154]])

In [123]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


In [124]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [125]:
print(data.max(axis=0)) #horizontal
print(data.max(axis=1)) #vertikal

[5 6]
[2 4 6]


In [126]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [127]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [132]:
data_col = np.array([[1, 2, 3, 4, 5, 6]])
print(data_col)
data_col2=data_col.T
print(data_col2)

[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [133]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [134]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [135]:
ndarr = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [141]:
print(np.ones((2,3,3)))

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [142]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [146]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])